#ifndef APP_CONFIG_DPMZM_H
#define APP_CONFIG_DPMZM_H

#include <stdbool.h>
#include <stdint.h>

/**
 * DPMZM pilot source selection.
 *
 * - EXTERNAL: two pilots are generated by external signal sources.
 * - ONBOARD:  the MCU/DAC path is responsible for injecting both pilots.
 */
typedef enum {
    DPMZM_PILOT_SOURCE_EXTERNAL = 0,
    DPMZM_PILOT_SOURCE_ONBOARD,
    DPMZM_PILOT_SOURCE_COUNT
} dpmzm_pilot_source_t;

/**
 * DPMZM scan dump mode.
 *
 * - METRICS: print only per-point summary metrics.
 * - RAW:     print raw ADC samples for each point.
 * - BOTH:    print both summary metrics and raw samples.
 */
typedef enum {
    DPMZM_DUMP_METRICS = 0,
    DPMZM_DUMP_RAW,
    DPMZM_DUMP_BOTH,
    DPMZM_DUMP_COUNT
} dpmzm_dump_mode_t;

/**
 * DPMZM open-loop experiment configuration.
 *
 * This configuration is intentionally separate from the legacy MZM
 * app_config_t so the new DPMZM work can evolve without disturbing the
 * existing single-MZM control path.
 */
typedef struct {
    /* DAC channel assignment for the three DPMZM bias paths */
    uint8_t bias_i_dac_channel;
    uint8_t bias_q_dac_channel;
    uint8_t bias_p_dac_channel;

    /* Default bias voltages for open-loop experiments */
    float bias_i_initial_v;
    float bias_q_initial_v;
    float bias_p_initial_v;

    /* Dual-pilot configuration */
    float pilot_i_freq_hz;
    float pilot_q_freq_hz;
    float pilot_i_amp_v;
    float pilot_q_amp_v;
    dpmzm_pilot_source_t pilot_source;

    /* Scan defaults */
    uint32_t scan_default_blocks;
    dpmzm_dump_mode_t dump_mode;
} app_config_dpmzm_t;

/**
 * Get the global DPMZM configuration instance.
 */
app_config_dpmzm_t *app_config_dpmzm_get(void);

/**
 * Reset the DPMZM configuration to default open-loop experiment values.
 */
void app_config_dpmzm_defaults(void);

#endif /* APP_CONFIG_DPMZM_H */
